[client]
showSidebarNavigation = false

[theme]

# Primary accent color for interactive elements.
primaryColor = "#6F1A07"

# Background color for the main content area.
backgroundColor = "#F7F3E3"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#AF9164"

# Color used for almost all text.
textColor = "#2B2118"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "monospace"